---
title: "Class 05: Data Visualization with GGPLOT"
author: "Michael Preston"
format: gfm
---

```{r}
# install.packages("ggplot2)
```

Plot cars dataset
```{r}
library(ggplot2)
ggplot(cars)
```

```{r}
ggplot(cars) + aes(speed, dist)
```
```{r}
ggplot(cars) + aes(speed, dist) + geom_point()
```
```{r}
ggplot(cars, aes(speed, dist, col='red')) + geom_point()
```

```{r}
ggplot(cars) + 
  aes(speed, dist) + 
  geom_point() + 
  geom_smooth() + 
  labs(title='Stopping distance v. speed',
       x='speed (MPH)',
       y='stopping distance (ft)')+ 
  theme_bw()
```

Plot Gene expression dataset
```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
```

```{r}
nrow(genes)
```

```{r}
colnames(genes)
```

```{r}
ncol(genes)
```

```{r}
table(genes['State'])
```
```{r}
127 / nrow(genes) *100
```

```{r}
ggplot(genes) +
  aes(Condition1, Condition2) +
  geom_point()
```

```{r}
ggplot(genes) +
  aes(Condition1, Condition2, col=State) +
  geom_point()
```

```{r}
p <- ggplot(genes) +
  aes(Condition1, Condition2, col=State) +
  geom_point() +
  scale_color_manual(values=c("blue", "gray", "red"))
p
```
```{r}
p + labs(title='Gene expression changes',
         y='treatment',
         x='control')
```

```{r}
# File location online
url <- "https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv"

gapminder <- read.delim(url)
```

```{r}
# install.packages("dplyr")
library(dplyr)
gapminder_2007 <- gapminder %>% filter(year==2007)
```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, 
      y=lifeExp,
      col=continent,
      size=pop) +
  geom_point(alpha=0.5)
```
Repeat for 1957
```{r}
gapminder_1957 <- gapminder %>% filter(year==1957)

ggplot(gapminder_1957) +
  geom_point(aes(x=gdpPercap, 
      y=lifeExp,
      col=continent,
      size=pop),
      alpha=0.7) +
  scale_size_area(max_size=10) +
  facet_wrap(~year)
```

